### ISSUE TITLE
mongolab heroku add-on discontinued...

### ISSUE THREAD

**Issue by GitToDaChoppa** [SpiffGreen/afrobeat#2]
Heroku errors when trying to deploy because the mongolab add-on has been discontinued...

is it required or is there a suggested alternative?

**Comment by SpiffGreen** [comment]
Hello @GitToDaChoppa,

The addon is not required for the application to run but MongoDB is required. So, a workaround is to configure the project to use another Heroku add-on, or just set the variable data required to connect to a MongoDB server, and that's it.

See this addon I found on Heroku - https://elements.heroku.com/addons/ormongo

If you will like to work on it, I'll be happy to see your PR.

Thanks.
